### PR TITLE
media type

### PR DESCRIPTION
**Pull request by JarbasAl**
possible solution for https://github.com/MycroftAI/mycroft-core/issues/2658

companion PR https://github.com/MycroftAI/mycroft-core/pull/2660

NOTE: this will break lang support except for en-us, this is because of migration from adapt to padatious to get rid of the ugly regex hack

To test 
install https://github.com/JarbasSkills/skill-hppodcraft/tree/cps_mediatype and verify 
- "read the call of cthulhu" uses common play with media type audiobook, 
- "play lovecraft podcast" should use podcast media type
- "play {story_name}" should trigger with generic media type
- "read lovecraft" should tie with skill-epic-horror-theatre if using  #36

install https://github.com/JarbasSkills/skil-old-world-radio/tree/cps_media_type and verify
- only triggers with media type radio
- "play vintage radio", "play old world radio"
- "play some radio" should trigger with low confidence

install https://github.com/MycroftAI/skill-npr-news/pull/90
- verify "play the news" triggers default feed with type news
- verify "play {station_name} news" triggers news station with type news
- "play {station_name}" should trigger with type generic

install https://github.com/JarbasSkills/skill-epic-horror-theatre/tree/feat/cps_media
- "read innsmouth" uses common play with media type audiobook, 
- "start audio drama" low confidence with media type audiobook, 
- "play the mountains of madness" should trigger with generic media type
- "read lovecraft" should tie with skill-hppodcraft if using  #36

### CODE REVIEW

**Comment by JarbasAl** [comment]
relates to https://github.com/MycroftAI/skill-playback-control/issues/18

"play music" with this PR becomes media type MUSIC and phrase is "" empty string

**Comment by krisgesling** [comment]
Hey this looks really good, and thanks for the many test cases to stretch its legs. 

In terms of breaking language support, would there be an issue with leaving the Adapt handler in until the next major release? The new Padatious intent should match with higher confidence unless the intent files don't exist for a language, then it should fallback to the old Adapt intent.

**Comment by krisgesling** [comment]
Hey just saw this again, what do you think of my comment above? 

I'm hesitant to break all Play intents for anyone not using "en-us"

**Comment by JarbasAl** [comment]
im thinking that might cause conflicts, adapt is "privileged" when matching intents, a padatious intent with 80% confidence in the case of this skill would still be pretty accurate but overrided, adapt essentially overmatches. due to the nature of capture groups the confidence of padatious might not be enough for proper selection

i think as a transition step we could register adapt only for other languages? not sure how well this fits in translate platform

A bigger issue (need to confirm this) is that trying to load the padatious intent files throw an error anyway if the files are missing for the configured language?

**Comment by krisgesling** [comment]
Yeah Padatious requires at least 95% confidence to beat Adapt so the training examples need to be pretty well defined.

If we can make a work around to register Adapt for certain languages that would be fine.

Is that an error if the language directory exists but the file doesn't?

**Comment by JarbasAl** [comment]
will re-open upon clarification of privacy ramifications of the latest mycroft partnership

code is free, you can copy and open a new PR if you do not want to wait for me re-opening it

**Pull request closed without merging**
